# Generated by Django 6.0.7 on 2026-07-23 07:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(blank=True, max_length=100, null=True)),
                ('ItemQuantity', models.CharField(blank=True, choices=[('Half', 'half'), ('Full', 'full')], max_length=20, null=True)),
                ('ItemPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='Payment_Status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='Payment_Type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='Status',
        ),
    ]
