# Generated by Django 6.0.7 on 2026-07-22 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustName', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Items', models.JSONField(blank=True, default=list, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('Car_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Preparing', 'preparing'), ('Accepted', 'accepted'), ('Ready To Collect', 'ready to collect'), ('Delivered', 'delivered')], default='Preparing', max_length=20)),
                ('Staff', models.CharField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'pending'), ('Paid', 'paid')], max_length=20, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('Online', 'online'), ('Offline', 'offline')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
